In [1]:
from requests import get, auth
from pprint import pprint
import pandas as pd
from config import clientid, clientsecret

In [2]:
baseurl = f'https://api.seatgeek.com/2/events?'

teams1 = ["boston-celtics",
"brooklyn-nets",
"new-york-knicks",
"philadelphia-76ers",
"toronto-raptors",
"golden-state-warriors",
"los-angeles-clippers",
"los-angeles-lakers",
"phoenix-suns",
"sacramento-kings",
"chicago-bulls",
"cleveland-cavaliers",
"detroit-pistons",
"indiana-pacers",
"milwaukee-bucks",
"dallas-mavericks",
"houston-rockets",
"memphis-grizzlies",
"san-antonio-spurs",
"atlanta-hawks",
"charlotte-hornets",
"miami-heat",
"orlando-magic",
"washington-wizards",
"denver-nuggets",
"minnesota-timberwolves",
"oklahoma-city-thunder",
"portland-trail-blazers",
"utah-jazz",
"new-orleans-pelicans"]


tix_prices = {}
home_coords = {}
next_matches = {}


for team in teams1:
    tix_prices[team]=[]
    home_coords[team]=[]
    next_matches[team]=[]
    params = {
        "client_id": clientid,
        "client_secret": clientsecret,
        "performers.slug":team
    }
    
    response = get(url=baseurl,params=params)
    data = response.json()
    events = data['events']
    for event in events:
        
        if event['performers'][0]['slug'] == team:
            avg_price = event['stats']['average_price']
            location = event['performers'][0]['location']
            
            tix_prices[team].append(avg_price)
            pprint(event['short_title'])
            home_coords[team] = location
            
        if event['performers'][0]['slug'] == team: 
            nextmatch = event['short_title']
            next_matches[team]=nextmatch
            break

'Pacers at Celtics'
'Cavaliers at Nets'
'Rockets at Knicks'
'Mavericks at 76ers'
'Pacers at Raptors'
'76ers at Warriors'
'Thunder at Clippers'
'Suns at Lakers'
'76ers at Suns'
'Suns at Kings'
'76ers at Bulls'
'Rockets at Cavaliers'
'Bucks at Pistons'
'Mavericks at Pacers'
'Spurs at Bucks'
'Warriors at Mavericks'
'Pistons at Rockets'
'Rockets at Grizzlies'
'Jazz at Spurs'
'Pacers at Hawks'
'Mavericks at Hornets'
'Knicks at Heat'
'Knicks at Magic'
'Nuggets at Wizards'
'Bucks at Nuggets'
'Hawks at Timberwolves'
'Hornets at Thunder'
'Bulls at Trail Blazers'
'Trail Blazers at Jazz'
'Hornets at Pelicans'

In [3]:
next_matches

{'boston-celtics': 'Pacers at Celtics',
 'brooklyn-nets': 'Cavaliers at Nets',
 'new-york-knicks': 'Rockets at Knicks',
 'philadelphia-76ers': 'Mavericks at 76ers',
 'toronto-raptors': 'Pacers at Raptors',
 'golden-state-warriors': '76ers at Warriors',
 'los-angeles-clippers': 'Thunder at Clippers',
 'los-angeles-lakers': 'Suns at Lakers',
 'phoenix-suns': '76ers at Suns',
 'sacramento-kings': 'Suns at Kings',
 'chicago-bulls': '76ers at Bulls',
 'cleveland-cavaliers': 'Rockets at Cavaliers',
 'detroit-pistons': 'Bucks at Pistons',
 'indiana-pacers': 'Mavericks at Pacers',
 'milwaukee-bucks': 'Spurs at Bucks',
 'dallas-mavericks': 'Warriors at Mavericks',
 'houston-rockets': 'Pistons at Rockets',
 'memphis-grizzlies': 'Rockets at Grizzlies',
 'san-antonio-spurs': 'Jazz at Spurs',
 'atlanta-hawks': 'Pacers at Hawks',
 'charlotte-hornets': 'Mavericks at Hornets',
 'miami-heat': 'Knicks at Heat',
 'orlando-magic': 'Knicks at Magic',
 'washington-wizards': 'Nuggets at Wizards',
 'denver-nuggets': 'Bucks at Nuggets',
 'minnesota-timberwolves': 'Hawks at Timberwolves',
 'oklahoma-city-thunder': 'Hornets at Thunder',
 'portland-trail-blazers': 'Bulls at Trail Blazers',
 'utah-jazz': 'Trail Blazers at Jazz',
 'new-orleans-pelicans': 'Hornets at Pelicans'}

In [4]:
nextgame_df=pd.DataFrame(list(next_matches.items()),columns=['team_name','next_homegame'])
nextgame_df['team_name']=nextgame_df['team_name'].str.replace('-'," ").str.title()

In [5]:
nextgame_df

                 team_name           next_homegame
0           Boston Celtics       Pacers at Celtics
1            Brooklyn Nets       Cavaliers at Nets
2          New York Knicks       Rockets at Knicks
3       Philadelphia 76Ers      Mavericks at 76ers
4          Toronto Raptors       Pacers at Raptors
5    Golden State Warriors       76ers at Warriors
6     Los Angeles Clippers     Thunder at Clippers
7       Los Angeles Lakers          Suns at Lakers
8             Phoenix Suns           76ers at Suns
9         Sacramento Kings           Suns at Kings
10           Chicago Bulls          76ers at Bulls
11     Cleveland Cavaliers    Rockets at Cavaliers
12         Detroit Pistons        Bucks at Pistons
13          Indiana Pacers     Mavericks at Pacers
14         Milwaukee Bucks          Spurs at Bucks
15        Dallas Mavericks   Warriors at Mavericks
16         Houston Rockets      Pistons at Rockets
17       Memphis Grizzlies    Rockets at Grizzlies
18       San Antonio Spurs           Jazz at Spurs
19           Atlanta Hawks         Pacers at Hawks
20       Charlotte Hornets    Mavericks at Hornets
21              Miami Heat          Knicks at Heat
22           Orlando Magic         Knicks at Magic
23      Washington Wizards      Nuggets at Wizards
24          Denver Nuggets        Bucks at Nuggets
25  Minnesota Timberwolves   Hawks at Timberwolves
26   Oklahoma City Thunder      Hornets at Thunder
27  Portland Trail Blazers  Bulls at Trail Blazers
28               Utah Jazz   Trail Blazers at Jazz
29    New Orleans Pelicans     Hornets at Pelicans

In [6]:
home_coords_list = {}
for key,value in home_coords.items():
    new_value = [value['lat'],value['lon']]
    home_coords_list[key] = new_value

In [7]:
coord_df = pd.DataFrame.from_dict(home_coords_list, orient='index', columns=['lat', 'lon'])
coord_df.index.name='team_name'
coord_df.reset_index(inplace=True)

coord_df['team_name']=coord_df['team_name'].str.replace('-'," ").str.title()

In [8]:
# homegame_avg = {}
# for key, value in tix_prices.items():
#     average=sum(value)/len(value)
#     homegame_avg[key]=round(average,2)
    
# homegame_avg

next_homeprice = {key: value[0] for key, value in tix_prices.items()}

In [9]:
prices_df=pd.DataFrame(list(next_homeprice.items()),columns=['team_name','avg_price_next_homegame'])
prices_df['team_name']=prices_df['team_name'].str.replace('-'," ").str.title()
prices_df

                 team_name  avg_price_next_homegame
0           Boston Celtics                      550
1            Brooklyn Nets                      180
2          New York Knicks                      410
3       Philadelphia 76Ers                      486
4          Toronto Raptors                      314
5    Golden State Warriors                      844
6     Los Angeles Clippers                      154
7       Los Angeles Lakers                      524
8             Phoenix Suns                      704
9         Sacramento Kings                      644
10           Chicago Bulls                      316
11     Cleveland Cavaliers                      167
12         Detroit Pistons                      184
13          Indiana Pacers                      227
14         Milwaukee Bucks                      651
15        Dallas Mavericks                      577
16         Houston Rockets                      102
17       Memphis Grizzlies                      209
18       San Antonio Spurs                      179
19           Atlanta Hawks                      271
20       Charlotte Hornets                      263
21              Miami Heat                      440
22           Orlando Magic                      227
23      Washington Wizards                      212
24          Denver Nuggets                      547
25  Minnesota Timberwolves                      131
26   Oklahoma City Thunder                      163
27  Portland Trail Blazers                      243
28               Utah Jazz                      225
29    New Orleans Pelicans                       93

In [10]:
mergeI = coord_df.merge(nextgame_df,on="team_name").merge(prices_df,on="team_name")
mergeI['team_name'] = mergeI['team_name'].replace('Philadelphia 76Ers', 'Philadelphia 76ers')

In [11]:
teams_df = pd.read_csv('team_info_common.csv')
teams_df['team_name'] = teams_df['team_name'].replace('LA Clippers', 'Los Angeles Clippers')
teams_df.head(30)

,team_id,season_year,team_name,team_conference,team_division,wins,losses,conf_rank,established
0,1610612737,2022-23,Atlanta Hawks,East,Southeast,32,32,8,1949
1,1610612738,2022-23,Boston Celtics,East,Atlantic,45,20,2,1946
2,1610612739,2022-23,Cleveland Cavaliers,East,Central,40,26,4,1970
3,1610612740,2022-23,New Orleans Pelicans,West,Southwest,31,33,9,2002
4,1610612741,2022-23,Chicago Bulls,East,Central,29,36,12,1966
5,1610612742,2022-23,Dallas Mavericks,West,Southwest,33,32,7,1980
6,1610612743,2022-23,Denver Nuggets,West,Northwest,45,19,1,1976
7,1610612744,2022-23,Golden State Warriors,West,Pacific,34,31,5,1946
8,1610612745,2022-23,Houston Rockets,West,Southwest,15,49,15,1967
9,1610612746,2022-23,Los Angeles Clippers,West,Pacific,34,33,8,1970
10,1610612747,2022-23,Los Angeles Lakers,West,Pacific,31,34,11,1948
11,1610612748,2022-23,Miami Heat,East,Southeast,34,31,7,1988
12,1610612749,2022-23,Milwaukee Bucks,East,Central,46,18,1,1968
13,1610612750,2022-23,Minnesota Timberwolves,West,Northwest,34,32,6,1989
14,1610612751,2022-23,Brooklyn Nets,East,Atlantic,36,28,6,1976
15,1610612752,2022-23,New York Knicks,East,Atlantic,39,27,5,1946
16,1610612753,2022-23,Orlando Magic,East,Southeast,27,38,13,1989
17,1610612754,2022-23,Indiana Pacers,East,Central,29,36,11,1976
18,1610612755,2022-23,Philadelphia 76ers,East,Atlantic,41,22,3,1949
19,1610612756,2022-23,Phoenix Suns,West,Pacific,36,29,4,1968
20,1610612757,2022-23,Portland Trail Blazers,West,Northwest,30,34,13,1970
21,1610612758,2022-23,Sacramento Kings,West,Pacific,37,26,3,1948
22,1610612759,2022-23,San Antonio Spurs,West,Southwest,16,49,14,1976
23,1610612760,2022-23,Oklahoma City Thunder,West,Northwest,30,34,12,1967
24,1610612764,2022-23,Washington Wizards,East,Southeast,30,34,10,1961
25,1610612765,2022-23,Detroit Pistons,East,Central,15,49,15,1948
26,1610612766,2022-23,Charlotte Hornets,East,Southeast,20,46,14,1988
27,1610612767,2022-23,Toronto Raptors,East,Atlantic,33,36,9,1995
28,1610612768,2022-23,Memphis Grizzlies,West,Southwest,41,26,2,1995
29,1610612769,2022-23,Utah Jazz,West,Northwest,33,36,11,1974

In [12]:
mergeII = teams_df.merge(mergeI, on='team_name')

In [13]:
mergeII.head(30)

,team_id,season_year,team_name,team_conference,team_division,wins,losses,conf_rank,established,lat,lon,next_homegame,avg_price_next_homegame
0,1610612737,2022-23,Atlanta Hawks,East,Southeast,32,32,8,1949,33.7566,-84.3969,Pacers at Hawks,271
1,1610612738,2022-23,Boston Celtics,East,Atlantic,45,20,2,1946,42.3653,-71.0618,Pacers at Celtics,550
2,1610612739,2022-23,Cleveland Cavaliers,East,Central,40,26,4,1970,41.4971,-81.6884,Rockets at Cavaliers,167
3,1610612740,2022-23,New Orleans Pelicans,West,Southwest,31,33,9,2002,29.9490,-90.0821,Hornets at Pelicans,93
4,1610612741,2022-23,Chicago Bulls,East,Central,29,36,12,1966,41.8806,-87.6740,76ers at Bulls,316
5,1610612742,2022-23,Dallas Mavericks,West,Southwest,33,32,7,1980,32.7904,-96.8103,Warriors at Mavericks,577
6,1610612743,2022-23,Denver Nuggets,West,Northwest,45,19,1,1976,39.7487,-105.0080,Bucks at Nuggets,547
7,1610612744,2022-23,Golden State Warriors,West,Pacific,34,31,5,1946,37.7704,-122.3870,76ers at Warriors,844
8,1610612745,2022-23,Houston Rockets,West,Southwest,15,49,15,1967,29.7508,-95.3621,Pistons at Rockets,102
9,1610612746,2022-23,Los Angeles Clippers,West,Pacific,34,33,8,1970,34.0430,-118.2670,Thunder at Clippers,154
10,1610612747,2022-23,Los Angeles Lakers,West,Pacific,31,34,11,1948,34.0430,-118.2670,Suns at Lakers,524
11,1610612748,2022-23,Miami Heat,East,Southeast,34,31,7,1988,25.7812,-80.1879,Knicks at Heat,440
12,1610612749,2022-23,Milwaukee Bucks,East,Central,46,18,1,1968,43.0417,-87.9162,Spurs at Bucks,651
13,1610612750,2022-23,Minnesota Timberwolves,West,Northwest,34,32,6,1989,44.9795,-93.2761,Hawks at Timberwolves,131
14,1610612751,2022-23,Brooklyn Nets,East,Atlantic,36,28,6,1976,40.6827,-73.9753,Cavaliers at Nets,180
15,1610612752,2022-23,New York Knicks,East,Atlantic,39,27,5,1946,40.7509,-73.9943,Rockets at Knicks,410
16,1610612753,2022-23,Orlando Magic,East,Southeast,27,38,13,1989,28.5392,-81.3839,Knicks at Magic,227
17,1610612754,2022-23,Indiana Pacers,East,Central,29,36,11,1976,39.7640,-86.1556,Mavericks at Pacers,227
18,1610612755,2022-23,Philadelphia 76ers,East,Atlantic,41,22,3,1949,39.9012,-75.1720,Mavericks at 76ers,486
19,1610612756,2022-23,Phoenix Suns,West,Pacific,36,29,4,1968,33.4458,-112.0710,76ers at Suns,704
20,1610612757,2022-23,Portland Trail Blazers,West,Northwest,30,34,13,1970,45.5316,-122.6670,Bulls at Trail Blazers,243
21,1610612758,2022-23,Sacramento Kings,West,Pacific,37,26,3,1948,38.5161,-121.4170,Suns at Kings,644
22,1610612759,2022-23,San Antonio Spurs,West,Southwest,16,49,14,1976,29.4271,-98.4374,Jazz at Spurs,179
23,1610612760,2022-23,Oklahoma City Thunder,West,Northwest,30,34,12,1967,35.4634,-97.5151,Hornets at Thunder,163
24,1610612764,2022-23,Washington Wizards,East,Southeast,30,34,10,1961,38.8981,-77.0209,Nuggets at Wizards,212
25,1610612765,2022-23,Detroit Pistons,East,Central,15,49,15,1948,42.3400,-83.0574,Bucks at Pistons,184
26,1610612766,2022-23,Charlotte Hornets,East,Southeast,20,46,14,1988,35.2248,-80.8403,Mavericks at Hornets,263
27,1610612767,2022-23,Toronto Raptors,East,Atlantic,33,36,9,1995,43.6435,-79.3791,Pacers at Raptors,314
28,1610612768,2022-23,Memphis Grizzlies,West,Southwest,41,26,2,1995,35.1383,-90.0522,Rockets at Grizzlies,209
29,1610612769,2022-23,Utah Jazz,West,Northwest,33,36,11,1974,40.7676,-111.9010,Trail Blazers at Jazz,225

In [14]:
mergeII.to_csv('merge_df.csv')